
from typing import Protocol, List, Optional, TypeVar
T = TypeVar("T")
class CrudRepo(Protocol[T]):
    def create(self, obj: T) -> T: ...
    def get(self, id_: str) -> Optional[T]: ...
    def list_all(self) -> List[T]: ...
    def update(self, obj: T) -> None: ...
    def delete(self, id_: str) -> None: ...
